# Generated by Django 4.0.3 on 2024-02-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_status_appointment_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='sold',
            new_name='status',
        ),
    ]
